ASSOCIATION RULES
The Objective of this assignment is to introduce students to rule mining techniques, particularly focusing on market basket analysis and provide hands on experience.
Dataset:
Use the Online retail dataset to apply the association rules.
Data Preprocessing:
Pre-process the dataset to ensure it is suitable for Association rules, this may include handling missing values, removing duplicates, and converting the data to appropriate format.  
Association Rule Mining:
•	Implement an Apriori algorithm using tool like python with libraries such as Pandas and Mlxtend etc.
•	 Apply association rule mining techniques to the pre-processed dataset to discover interesting relationships between products purchased together.
•	Set appropriate threshold for support, confidence and lift to extract meaning full rules.
Analysis and Interpretation:
•	Analyse the generated rules to identify interesting patterns and relationships between the products.
•	Interpret the results and provide insights into customer purchasing behaviour based on the discovered rules.
Interview Questions:
1.	What is lift and why is it important in Association rules?
2.	What is support and Confidence. How do you calculate them?
3.	What are some limitations or challenges of Association rules mining?

As the data given was clumsy I used a delimiter with coma(,) to seperate all items and gave header = None to give index column wise.

In [7]:
import pandas as pd
df = pd.read_excel("Online retail copy.xlsx",header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
data = pd.get_dummies(df,dtype='int')
data

,0_almonds,0_antioxydant juice,0_asparagus,0_avocado,0_babies food,0_bacon,0_barbecue sauce,0_black tea,0_blueberries,0_body spray,...,16_antioxydant juice,16_french fries,16_frozen smoothie,17_frozen smoothie,17_protein bar,17_spinach,18_cereals,18_mayonnaise,18_spinach,19_olive oil
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

get_dummies converts categorical variables into 0 and 1 so that machine learning algorithms can be applied.

In [32]:
import warnings
warnings.filterwarnings('ignore') #to ignore warnings
from mlxtend.frequent_patterns import apriori, association_rules
frequent_items = apriori(data, min_support = 0.001, use_colnames=True)
frequent_items

       support                                           itemsets
0     0.001466                                        (0_almonds)
1     0.002400                              (0_antioxydant juice)
2     0.007599                                        (0_avocado)
3     0.001200                                      (0_black tea)
4     0.003066                                       (0_brownies)
...        ...                                                ...
1777  0.001333             (3_spaghetti, 5_milk, 4_mineral water)
1778  0.001466        (5_olive oil, 3_spaghetti, 4_mineral water)
1779  0.001067             (6_milk, 4_spaghetti, 5_mineral water)
1780  0.001067  (2_ground beef, 1_frozen vegetables, 3_spaghet...
1781  0.001067  (2_ground beef, 1_tomatoes, 3_spaghetti, 4_min...

[1782 rows x 2 columns]

In [24]:
rules = association_rules(frequent_items,metric = 'lift',min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(0_shrimp),(1_frozen vegetables),0.043328,0.031196,0.010265,0.236923,7.594701,1.0,0.008914,1.269602,0.907656,0.159751,0.212352,0.282991
1,(1_frozen vegetables),(0_shrimp),0.031196,0.043328,0.010265,0.329060,7.594701,1.0,0.008914,1.425868,0.896290,0.159751,0.298673,0.282991
2,(0_spaghetti),(1_mineral water),0.047194,0.064525,0.013332,0.282486,4.377947,1.0,0.010286,1.303773,0.809800,0.135501,0.232995,0.244549
3,(1_mineral water),(0_spaghetti),0.064525,0.047194,0.013332,0.206612,4.377947,1.0,0.010286,1.200933,0.824803,0.135501,0.167314,0.244549
4,(1_ground beef),(2_spaghetti),0.038795,0.037195,0.011865,0.305842,8.222653,1.0,0.010422,1.387011,0.913837,0.185031,0.279025,0.312419
5,(2_spaghetti),(1_ground beef),0.037195,0.038795,0.011865,0.318996,8.222653,1.0,0.010422,1.411454,0.912318,0.185031,0.291511,0.312419
6,(2_mineral water),(1_spaghetti),0.049993,0.054793,0.017731,0.354667,6.472882,1.0,0.014992,1.464681,0.890004,0.203675,0.317257,0.339134
7,(1_spaghetti),(2_mineral water),0.054793,0.049993,0.017731,0.323601,6.472882,1.0,0.014992,1.404506,0.894523,0.203675,0.288006,0.339134
8,(2_spaghetti),(3_mineral water),0.037195,0.026796,0.012798,0.344086,12.840743,1.0,0.011802,1.483737,0.957746,0.250000,0.326026,0.410849
9,(3_mineral water),(2_spaghetti),0.026796,0.037195,0.012798,0.477612,12.840743,1.0,0.011802,1.843084,0.947513,0.250000,0.457431,0.410849

Observe index 9, it is the best association rule as  its lift ratio is higher.

1.  What is lift and why is it important in Association rules?
 A. Lift is a metric used in association rule mining. If the Lift ratio is higher than it indicates a better rule.
    Lift is the ratio of confidence with benchmark confidence.The benchmark confidence value for a rule is the         support for the consequent divided by the number of transactions in the database.

2.	What is support and Confidence. How do you calculate them?
 A. Support is a metric used in association rule mining to measure the frequency of occurrence of an itemset in a      dataset. It is measured by (Number of transactions with both antecedent and consequent item sets) divided by       Total number of transactions).
    Confidence is measure of reliability or strength of a discovered relationship between two items. It is             calculated by (Number of transactions with both antecedent and consequent) divided by (Number of transactions      with antecedent).
    
3.	What are some limitations or challenges of Association rules 
 A. While Association rule mining is powerful It does have some limitations:
     It generates large number of rules which are mostly irrelevant or unimportant.
     It requires predefined thresholds for minimum support and confidence which are difficult to set manually.
     High Computational complexity